# Changes here will be overwritten by Copier
_commit: 2.5.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: tom.cobb@diamond.ac.uk
author_name: Tom Cobb
component_lifecycle: production
component_owner: group:default/accelerator-controls
component_type: library
description: Asynchronous Channel Access client for asyncio and Python using libca
    via ctypes
distribution_name: aioca
docker: false
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: aioca
pypi: true
repo_name: aioca
type_checker: mypy
