repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"] # uv.lock is more than 500kB
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      # Run the linter.
      - id: ruff
        name: lint with ruff
        language: system
        entry: ruff check --force-exclude --fix
        types: [python]

      # Run the formatter.
      - id: ruff-format
        name: format with ruff
        language: system
        entry: ruff check
        types: [python]
        require_serial: true

      # Make sure lock file satisfies dependencies in pyproject.toml.
      - id: uv-sync
        name: update uv.lock and venv
        pass_filenames: false
        language: system
        entry: uv sync
        files: ^(uv\.lock|pyproject\.toml)$
