name: Docs CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install Packages
        run: sudo apt-get install graphviz

      - name: Install Python Dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy --python $(which python) && pipenv graph

      - name: Build Docs
        run: pipenv run docs

      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ github.ref }}
          seperator: /

      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: mv build/html ".github/pages/${{ steps.split.outputs._2 }}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'dls-controls' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/pages
          keep_files: true

      - name: Enable gh-pages
        # If we just pushed something, make sure it is visible
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pages \
          --header 'Accept: application/vnd.github.switcheroo-preview+json' \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data '{"source":{"branch":"gh-pages","path":"/"}}' \
